version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    network_mode: "host"

  redis:
    image: redis
    container_name: redis
    network_mode: "host"

  lila-ui:
    image: madkonix/noss-lila-ui:alpine-dev
    container_name: lila-ui
    volumes:
      - /path/to/lila/:/root/lila/
    depends_on:
      - mongo
      - redis
    network_mode: "host"
